### ISSUE TITLE
引数の入力の仕方がわからない

### ISSUE THREAD

**Issue by HappyMana** [HappyMana/text_to_speech#1]
rosservice call /sttの引数の入力の仕方がよくわからない
エラー内容:responded with an error: error processing request: 'ttsRequest' object has no attribute 'sentence'

**Comment by HappyMana** [comment]
引数の入力の仕方じゃなくてノードの中身がだめなのかも。
クライアント側の入力：rosservice call tts "hello"
クライアント側のエラー：
ERROR: service [/tts] responded with an error: error processing request: 'ttsRequest' object has no attribute 'sentence'
サーバー側のエラー：
['Traceback (most recent call last):\n', '  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 632, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/mana/catkin_ws/src/text_to_speech/src/tts_server.py", line 27, in execute\n    synthesis_input = texttospeech.SynthesisInput(text=data.sentence)\n', "AttributeError: 'ttsRequest' object has no attribute 'sentence'\n"]
